[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^6.21.4
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    beegee-tokyo/DHT sensor library for ESPx@^1.19
